apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.serviceName }}
  description: "Microservicio ${{ values.serviceName }} - generado mediante Backstage Golden Path"

  annotations:
    github.com/project-slug: Anatarqu/${{ values.serviceName }}
    backstage.io/techdocs-ref: dir:.

  tags:
    - nodejs
    - microservicio
    - golden-path

spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: plataforma-uniandes
